import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
          <ThemeProvider
            defaultTheme="system"
            storageKey="notion-theme"
          >
            <div className="min-h-screen bg-background text-foreground">
              <Header/>
              <div className="flex min-h-screen">
                {/* sidebar */}
                <Sidebar/>
                <div className="flex-1 p-4 bg-background transition-colors overflow-y-auto scrollbar-hide">
                    {children}
                </div>
              </div>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
